### ISSUE TITLE
Building queries

### ISSUE THREAD

**Issue by staticdreams** [spf2/FirebaseAdapter#2]
Hi!

I really like the adapter, by so far it has been limited to simple use, such retrieving all the record I have.
How would I got about creating more complex queries?

For instance I need to get all records in my news collection where 'published' == true 
Or only view news created by a particular user? or even a currently logged in user?

Thanks for this wonderful Firebase adapter :)

**Comment by spf2** [comment]
Hi,

I'm glad you're finding the adapter helpful.   [This section](/spf2/FirebaseAdapter#multiple-sections-with-multiple-streams) has some info on how to use the QueryBuilder.  For something like published=true, you'd do something like `query.ordering = .Child("published")` and `query.start = true`.  This just passes the query to the underlying Firebase protocol (look for Querying Data [here](https://www.firebase.com/docs/ios/guide/retrieving-data.html)).

If you want to do user-based querying, this kind of thing might work, but you may be better served by copying (denormalizing) your data.  There's more about that [here](https://www.firebase.com/blog/2013-04-12-denormalizing-is-normal.html).

**Comment by staticdreams** [comment]
Thank you! It worked!)
