### ISSUE TITLE
FirebaseAdapter not available in Cocoapods

### ISSUE THREAD

**Issue by bentacles** [spf2/FirebaseAdapter#3]
The readme states to add 
`pod 'FirebaseAdapter', '~> 0.3'`

into the PodFile.  However I get the error, 

> [!] Unable to find a specification for `FirebaseAdapter`

I searched on [CocoaPods](https://cocoapods.org/?q=firebaseadapter)  and came up empty.

**Comment by spf2** [comment]
Hi,

Sorry, I have not added it to cocoapods directory yet. You should still be able to use FirebaseAdapter, but you'll need to fetch the code with `git clone https://github.com/spf2/FirebaseAdapter.git`. Ping this bug if you need more help from there.

**Comment by bentacles** [comment]
No worries.  I created a submodule in my git project;

`git submodule add https://github.com/spf2/FirebaseAdapter.git`

Then added the following to the Podfile:

> pod 'FirebaseAdapter’, :path=>’./FirebaseAdapter/’

**Comment by bentacles** [comment]
I'll close this issue.
